domain_dict_path: "../../common/domains_dict.json"
domain_group_dict_path: "../../common/domain_groups.json"

context_length: 256
forecast_horizon: 96

output_base_dir: "../../data/time-moe/ratfm/reconstruction/before_merge"
output_test_dir: "../../data/moment/ratfm/reconstruction/eval"

