base_dir: "../../../../"
main_script: "models/time-moe/settings/ratfm/main_ratfm.py"
domain_dict_path: "common/domains_dict.json"
base_data_path: "data/time-moe/ratfm/train/"
test_data_path: "data/time-moe/ratfm/eval/"
save_base: "results/time-moe/ratfm"

context_length: 512
forecast_horizon: 96
data_stride_len: 96
batch_size: 32
num_train_epochs: 10
normalization_method: "none"

device: "cuda:1"

