base_dir: "../../../../"
main_script: "models/time-moe/settings/ratfm/main_ratfm_without_training.py"
domain_dict_path: "common/domains_dict.json"
test_data_path: "data/time-moe/ratfm/eval/"
save_base: "results/time-moe/ratfm_without_training/"

context_length: 512
forecast_horizon: 96
data_stride_len: 96
batch_size: 32

device: "cuda:1"
