base_dir: "../../../../"
domain_dict_path: "common/domain_groups.json"
base_data_path: "data/moment/domain_group/"
save_base: "results/moment/in_domain_FT/"

context_length: 512
forecast_horizon: 96
data_stride_len: 96
batch_size: 32
num_train_epochs: 10

device: "cuda:1"


