
base_dir: "../../../../"
domain_dict_path: "common/domains_dict.json"
base_data_path: "data/moment/ratfm/train/"
test_data_path: "data/moment/ratfm/eval/"
save_base: "results/moment/ratfm"

context_length: 208
forecast_horizon: 96
data_stride_len: 96
batch_size: 32
num_train_epochs: 10

device: "cuda:1"


