base_dir: "../../../../"
domain_dict_path: "common/domains_dict.json"
save_base: "results/moment/zero_shot/"

context_length: 512
forecast_horizon: 96
data_stride_len: 96
batch_size: 32

device: "cuda:3"

